### ISSUE TITLE
Windows defender tags as Program:Win32/Beareuws.A!ml

### ISSUE THREAD

**Issue by RandomUser99** [deluxghost/rva#1]
![vus](https://user-images.githubusercontent.com/1633786/103146981-4a052280-4748-11eb-8b2f-721f6e2541d0.PNG)

file: C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\rva.exe

**Comment by deluxghost** [comment]
windows defender sucks when it scan self written programs... it thought rva is a trojan just because rva write log file to temp folder, that's why I change log folder to appdata (but obviously temp is better)

in the screenshot, wd says rva has potentially unwanted behavior, at least it doesn't report rva as trojan again. but as such a tiny tool, rva doesn't even use any network connection, it stays at background and only query and set app volumes. you can also use virustotal scan the behavior of rva.exe

rva is open source, and easily built by yourself. if wd haven't delete it you can add it to the trust list, or clone this project and build yourself, or just don't waste time on this, wait rockstar fix the damn volume bug.

if you find more useful info, share with me.
